spring.application.name=cardwise-backend
server.port=${PORT:8080}
cardwise.catalogue.mode=${CARDWISE_CATALOGUE_MODE:DEMO}

# PostgreSQL database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cardwise_db}
spring.datasource.username=${DB_USERNAME:cardwise_user}
spring.datasource.password=${DB_PASSWORD:}

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true